spring:
  profiles:
    active: local
    group:
      local: local_server, common, secret
      blue: blue_server, common, secret
      green: green_server, common, secret

---

spring:
  config:
    activate:
      on-profile: local_server
server:
  port: 8080
client:
  address: http://localhost:3000

---

spring:
  config:
    activate:
      on-profile: blue_server
server:
  port: 8080
client:
  address: http://localhost:3000

---

spring:
  config:
    activate:
      on-profile: green_server
server:
  port: 9090
client:
  address: http://localhost:3000
---

spring:
  config:
    activate:
      on-profile: common

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  mapper-locations:
    - mappers/*.xml
    - mappers/user/*.xml

---

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
